### Вывести приветствие
GET http://localhost:8080/calculator

### Вывести сумму 5+5
GET http://localhost:8080/calculator/plus?num1=5&num2=5

### Вывести разницу 5-5
GET http://localhost:8080/calculator/minus?num1=5&num2=5

### Вывести произведение 5*5
GET http://localhost:8080/calculator/multiply?num1=5&num2=5

### Вывести результат деления
GET http://localhost:8080/calculator/divide?num1=5&num2=0
